---
- name: Ensure Homebrew is installed
  command: which brew
  register: brew_check
  failed_when: false
  changed_when: false

- name: Install Homebrew if not installed
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - git

- name: Install Utilities
  package:
    name:
      - bat
      - eza
      - fzf
      - ripgrep
      - tmux
      - tree
      - stow
      - wget
      - xh
      - zoxide
    state: present

- name: Install Languages
  package:
    name:
      - go
      - node
    state: present
