version: 3

tasks:

  jaeger:
    desc: Start Jaeger locally and open the browser.
    cmds:
      - defer: open "http://localhost:16686"
      - |
        docker run -d --rm --name jaeger \
          -e COLLECTOR_OTLP_ENABLED=true \
          -p 16686:16686 \
          -p 4317:4317 \
          -p 4318:4318 \
          jaegertracing/all-in-one:1.75.0

  nvim:clean:
    desc: Remove generated file that can get out of sync after package upgrades.
    cmds:
      - rm ~/.local/share/nvim/lazy/nvim-treesitter/parser/*.so
      - rm ~/.local/share/nvim/site/queries/*
