version: 3

tasks:

  jaeger:
    cmds:
      - defer: open "http://localhost:16686"
      - |
        docker run -d --rm --name jaeger \
          -e COLLECTOR_OTLP_ENABLED=true \
          -p 16686:16686 \
          -p 4317:4317 \
          -p 4318:4318 \
          jaegertracing/all-in-one:latest
