#!/usr/bin/env bash

# Configure iTerm2 to look in ~/.config for settings.
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.config/iterm2_profile"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
