#!/usr/bin/env bash

# MacOS ships with an out-of-date version of tmux-256color. screen-256color
# works failry well, but does not support italic text. Run this script to
# install a current tmux-256.

# Links
# https://www.rockyourcode.com/til-how-to-fix-cannot-read-termcap-database-with-tmux-and-kitty-on-macos/
# https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
# https://jdhao.github.io/2018/10/19/tmux_nvim_true_color/

# Download terminfo provided by the tmux maintainers:
curl -sSL https://gist.github.com/nicm/ea9cf3c93f22e0246ec858122d9abea1 > tmux-256color

# Compile tmux-256color terminal info:
/usr/bin/tic -xe tmux-256color terminfo.src

# Verify that terminfo returns the correct value (it should not be null):
infocmp -x tmux-256color

