version: 3

tasks:

  ansible:
    desc: "Run the playbook to install and configure dotfiles"
    dir: ./ansible
    cmds:
      - ansible-playbook main.yml

  sketchybar-plugins:
    desc: "Build plugins for Sketchybar"
    dir: ~/.config/sketchybar/plugins
    cmds:
      - go build -o aerospace ./aerospace.go
      - sketchybar --update
