---
- name: Ensure Homebrew is installed
  command: which brew
  register: brew_check
  failed_when: false
  changed_when: false

- name: Install Homebrew if not installed
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Add custom Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - FelixKratz/formulae #borders
    - nikitabobko/tap     #aerospace

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - git

- name: Install Utilities
  package:
    name:
      - bat
      - eza
      - fd
      - fzf
      - ripgrep
      - tmux
      - tree
      - stow
      - watch
      - wget
      - xh
      - yazi
      - zoxide
    state: present

- name: Install Languages
  package:
    name:
      - go
      - node
    state: present

- name: Install Azure and Kubernetes Utilities
  package:
    name:
      - azure-cli
      - krew
      - kube-ps1
    state: present

# Update PATH to include Krew plugins (for the current Ansible run)
- name: Set Krew PATH for Ansible
  set_fact:
    krew_path: "{{ ansible_env.HOME }}/.krew/bin"

# Install Krew plugins
- name: Install Krew plugins
  shell: "PATH={{ ansible_env.PATH }}:{{ krew_path }} kubectl krew install {{ item }}"
  register: krew_plugin_install
  changed_when: "'Plugin installed successfully' in krew_plugin_install.stdout"
  failed_when:
    - krew_plugin_install.rc != 0
    - "'already installed' not in krew_plugin_install.stderr"
  loop:
    - ctx
    - neat
    - ns
    - resource-capacity
    - stern

- name: Install GUI Applications
  package:
    name:
      - aerospace
      - borders
      - raycast
      - sketchybar
    state: present
