---
- name: Ensure GNU Stow is installed
  package:
    name: stow
    state: present

- name: Run stow for each package
  command:
    cmd: "stow {{ item }}"
  loop:
    - aerospace
    - bin
    - borders
    - ghostty
    - git
    - hammerspoon
    - ideavim
    - k9s
    - nvim
    - sketchybar
    - task
    - tmux
    - yazi
    - zsh
  args:
    chdir: "{{ stow_dir }}"
