[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.top =        [{ monitor.main = 100 }, { monitor."built-in" = 0 }, 0]
outer.right =      [{ monitor.main = 400 }, { monitor."built-in" = 0 }, 0]
outer.bottom =     [{ monitor.main = 100 }, { monitor."built-in" = 0 }, 0]
outer.left =       [{ monitor.main = 400 }, { monitor."built-in" = 0 }, 0]
