[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.top =        [{ monitor.main = 20 }, { monitor."built-in" = 0 }, 0]
outer.right =      [{ monitor.main = 20 }, { monitor."built-in" = 0 }, 0]
outer.bottom =     [{ monitor.main = 20 }, { monitor."built-in" = 0 }, 0]
outer.left =       [{ monitor.main = 20 }, { monitor."built-in" = 0 }, 0]
