[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.top =        [{ monitor.main = 100 }, { monitor."built-in" = 5 }, 0]
outer.right =      [{ monitor.main = 800 }, { monitor."built-in" = 5 }, 0]
outer.bottom =     [{ monitor.main = 100 }, { monitor."built-in" = 5 }, 0]
outer.left =       [{ monitor.main = 800 }, { monitor."built-in" = 5 }, 0]
