[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.top =        [{ monitor."built-in" = 5 }, { monitor.main = 100 }, 0]
outer.right =      [{ monitor."built-in" = 5 }, { monitor.main = 800 }, 0]
outer.bottom =     [{ monitor."built-in" = 5 }, { monitor.main = 100 }, 0]
outer.left =       [{ monitor."built-in" = 5 }, { monitor.main = 800 }, 0]
